updatee wasm-bindgen
Got this message:

  nailing-cargo: invoking: /home/ian/Rustup/Game/Build/wasm-pack/target/debug/wasm-pack --cargo-path=/bin/echo build --out-dir=../target/packed-wasm wasm -t no-modules --release
  [1m[2m[INFO][0m: Checking for the Wasm target...
  [1m[2m[INFO][0m: Compiling to Wasm...
  build --lib --release --target wasm32-unknown-unknown
  :-) [1m[2m[WARN][0m: origin crate has no README
  [1m[2m[INFO][0m: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
  [1m[2m[INFO][0m: Installing wasm-bindgen...
  error:

  it looks like the Rust project used to create this wasm file was linked against
  a different version of wasm-bindgen than this binary:

    rust wasm file: 0.2.69
       this binary: 0.2.70 (b6355c270)

  Currently the bindgen format is unstable enough that these two version must
  exactly match, so it's required that these two version are kept in sync by
  either updating the wasm-bindgen dependency or this binary. You should be able
  to update the wasm-bindgen dependency with:

      cargo update -p wasm-bindgen

  or you can update the binary with

      cargo install -f wasm-bindgen-cli

  if this warning fails to go away though and you're not sure what to do feel free
  to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!

  Error: Running the wasm-bindgen CLI
  Caused by: failed to execute `wasm-bindgen`: exited with exit code: 1
    full command: "/home/rustcargo/.cache/.wasm-pack/wasm-bindgen-454f7c61ea4f4e72/wasm-bindgen" "/volatile/rustcargo/Rustup/Game/server/target/wasm32-unknown-unknown/release/otter_wasm.wasm" "--out-dir" "wasm/../target/packed-wasm" "--typescript" "--target" "no-modules"
  nailing-cargo: really failed (exit status 256)
  nailing-cargo: unnailed.  status 1.
  make: *** [Makefile:199: stamp/wasm-pack] Error 1

  Compilation exited abnormally with code 2 at Tue Jan 26 22:35:13

This message appeared after a `make clean` and then rerunning the
build "fixed" it; `make clean` produced it again.  This is not
confidence-inspiring.

cargo update fixed it.

But I thought wasm-pack was supposed to handle this properly.  Not
sure why I am using it, now.

Signed-off-by: Ian Jackson <ijackson@chiark.greenend.org.uk>